export const MATERNITY_PACKAGE_CONSTANT = {
  CREATED: 'Tạo gói dịch vụ thành công',
  UPDATED: 'Cập nhật gói dịch vụ thành công',
  DELETED: 'Xóa gói dịch vụ thành công',
  FOUND: 'Lấy danh sách gói dịch vụ thành công',
  DETAIL_FOUND: 'Lấy chi tiết gói dịch vụ thành công',
  NOT_FOUND: 'Không tìm thấy gói dịch vụ',
  CODE_EXISTS: 'Mã gói dịch vụ đã tồn tại',
  NAME_EXISTS: 'Tên gói dịch vụ đã tồn tại',
  FACILITY_SERVICE_INVALID: 'Dịch vụ tại cơ sở không hợp lệ',
  FACILITY_SERVICE_UNAVAILABLE: 'Dịch vụ tại cơ sở đang ngừng cung cấp',
  FACILITY_SERVICE_NOT_IN_PACKAGE_FACILITY:
    'Dịch vụ trong gói phải thuộc cùng cơ sở với gói',
  PACKAGE_ITEM_DUPLICATED: 'Gói không được chứa trùng một dịch vụ tại cơ sở trong cùng một nhóm',
  QUANTITY_SERVICES_REQUIRED: 'Gói theo số lượt phải có ít nhất một dịch vụ',
  QUANTITY_STAGES_INVALID:
    'Gói theo số lượt không được khai báo các mốc lịch trình',
  SCHEDULE_STAGES_REQUIRED: 'Gói theo lịch trình phải có ít nhất một mốc',
  SCHEDULE_ROOT_SERVICES_INVALID:
    'Gói theo lịch trình phải khai báo dịch vụ bên trong từng mốc',
  STAGE_SERVICES_REQUIRED: 'Mỗi mốc/lộ trình trong gói phải có ít nhất một dịch vụ',
  STAGE_WEEK_REQUIRED: 'Mốc tuần thai phải có tuần bắt đầu và tuần kết thúc',
  STAGE_WEEK_RANGE_INVALID: 'Tuần bắt đầu phải nhỏ hơn hoặc bằng tuần kết thúc',
  FACILITY_ID_INVALID: 'Mã cơ sở phải là số nguyên dương',
  SERVICE_ID_INVALID: 'Mã dịch vụ phải là số nguyên dương',
  FACILITY_SERVICE_ID_INVALID: 'Mã dịch vụ tại cơ sở phải là số nguyên dương',
  SERVICE_REFERENCE_REQUIRED: 'Mỗi quyền lợi phải chọn một dịch vụ',
  INCLUDED_QUANTITY_INVALID: 'Số lượt sử dụng phải là số nguyên từ 1 đến 100',
  SERVICE_CLASSIFICATION_INVALID: 'Dịch vụ phải được chọn là bắt buộc hoặc tùy chọn',
  SORT_ORDER_INVALID: 'Thứ tự hiển thị phải là số nguyên từ 0 đến 1000',
  STAGE_NAME_INVALID: 'Tên mốc phải có từ 2 đến 255 ký tự',
  STAGE_TYPE_INVALID: 'Loại mốc không hợp lệ',
  STAGE_WEEK_INVALID: 'Tuần thai phải là số nguyên từ 1 đến 45',
  STAGE_GOAL_TOO_LONG: 'Mục tiêu của mốc không được vượt quá 3000 ký tự',
  NAME_INVALID: 'Tên gói phải có từ 2 đến 200 ký tự',
  DESCRIPTION_TOO_LONG: 'Mô tả gói không được vượt quá 3000 ký tự',
  TYPE_INVALID: 'Loại gói dịch vụ không hợp lệ',
  PRICE_INVALID: 'Giá gói phải là số tiền không âm, tối đa 13 chữ số phần nguyên và 2 chữ số thập phân',
  DURATION_INVALID: 'Thời hạn gói phải là số nguyên từ 1 đến 2000 ngày',
  PRIORITY_INVALID: 'Độ ưu tiên phải là số nguyên từ 0 đến 100',
  STATUS_INVALID: 'Trạng thái gói dịch vụ không hợp lệ',
  SEARCH_TOO_LONG: 'Từ khóa tìm kiếm không được vượt quá 100 ký tự',
  PAGE_INVALID: 'Số trang phải là số nguyên dương',
  LIMIT_INVALID: 'Số bản ghi mỗi trang phải là số nguyên từ 1 đến 200',
};
