export const PACKAGE_SERVICE_CONSTANT = {
  CREATED: 'Thêm dịch vụ vào gói thành công',
  BULK_CREATED: 'Thêm nhiều dịch vụ vào gói thành công',
  UPDATED: 'Cập nhật dịch vụ trong gói thành công',
  DELETED: 'Xóa dịch vụ khỏi gói thành công',
  FOUND: 'Lấy danh sách dịch vụ trong gói thành công',
  DETAIL_FOUND: 'Lấy chi tiết dịch vụ trong gói thành công',
  NOT_FOUND: 'Không tìm thấy dịch vụ trong gói',
  ALREADY_EXISTS: 'Gói này đã có dịch vụ đó',
  PACKAGE_INACTIVE: 'Gói dịch vụ không hoạt động',
  SERVICE_INACTIVE: 'Dịch vụ gốc không hoạt động',
  FACILITY_SERVICE_INACTIVE: 'Dịch vụ tại cơ sở đang ngừng cung cấp',
  BULK_DUPLICATED_IN_PAYLOAD: 'Danh sách thêm vào gói có dịch vụ tại cơ sở bị trùng',
  SELECTED_FACILITIES_REQUIRED: 'Vui lòng chọn ít nhất một cơ sở khi phạm vi áp dụng là các cơ sở được chọn',
  CANNOT_DELETE_USED_PACKAGE_SERVICE: 'Dịch vụ trong gói đã phát sinh quyền lợi cho bệnh nhân, không thể xóa cứng',
  PACKAGE_ID_INVALID: 'Mã gói dịch vụ phải là số nguyên dương',
  FACILITY_SERVICE_ID_INVALID: 'Mã dịch vụ tại cơ sở phải là số nguyên dương',
  FACILITY_ID_INVALID: 'Mã cơ sở phải là số nguyên dương',
  SERVICE_TYPE_ID_INVALID: 'Mã loại dịch vụ phải là số nguyên dương',
  INCLUDED_QUANTITY_INVALID: 'Số lượt sử dụng phải là số nguyên từ 1 đến 100',
  CLASSIFICATION_INVALID: 'Dịch vụ phải được chọn là bắt buộc hoặc tùy chọn',
  FACILITY_SCOPE_INVALID: 'Phạm vi cơ sở áp dụng không hợp lệ',
  SORT_ORDER_INVALID: 'Thứ tự hiển thị phải là số nguyên từ 0 đến 1000',
  SERVICES_REQUIRED: 'Danh sách dịch vụ trong gói phải có ít nhất một dịch vụ',
  SEARCH_INVALID: 'Từ khóa tìm kiếm phải là chuỗi hợp lệ',
  PAGE_INVALID: 'Số trang phải là số nguyên dương',
  LIMIT_INVALID: 'Số bản ghi mỗi trang phải là số nguyên từ 1 đến 200',
};
