export const RESPONSE_MESSAGES = {
  SUCCESS: 'Thành công',
  AUTH_REGISTERED: 'Đăng ký tài khoản thành công',
  AUTH_LOGGED_IN: 'Đăng nhập thành công',
  AUTH_REFRESHED: 'Làm mới mã xác thực thành công',
  AUTH_PROFILE_RETRIEVED: 'Lấy thông tin tài khoản xác thực thành công',
  PROFILE_RETRIEVED: 'Lấy thông tin hồ sơ thành công',
  PROFILE_UPDATED: 'Cập nhật hồ sơ thành công',
  MANAGEMENT_PROFILE_UPDATED: 'Cập nhật hồ sơ thành công.',
  MANAGEMENT_PASSWORD_CHANGED: 'Đổi mật khẩu thành công.',
  USERS_RETRIEVED: 'Lấy danh sách tài khoản thành công',
  USER_CREATED: 'Tạo tài khoản thành công',
  USER_RETRIEVED: 'Lấy thông tin tài khoản thành công',
  USER_UPDATED: 'Cập nhật tài khoản thành công',
  USER_DELETED: 'Xóa tài khoản thành công',
  STAFF_PROFILE_CREATED: 'Tạo hồ sơ nhân viên thành công.',
  ROLES_RETRIEVED: 'Lấy danh sách vai trò thành công',
  ROLE_CREATED: 'Tạo vai trò thành công',
  ROLE_RETRIEVED: 'Lấy thông tin vai trò thành công',
  ROLE_UPDATED: 'Cập nhật vai trò thành công',
  ROLE_DELETED: 'Xóa vai trò thành công',
  PERMISSIONS_RETRIEVED: 'Lấy danh sách quyền thành công',
  PERMISSION_CREATED: 'Tạo quyền thành công',
  PERMISSION_RETRIEVED: 'Lấy thông tin quyền thành công',
  PERMISSION_UPDATED: 'Cập nhật quyền thành công',
  PERMISSION_DELETED: 'Xóa quyền thành công',
  PUBLIC_SETTINGS_RETRIEVED: 'Lấy cấu hình công khai thành công',
  SETTINGS_RETRIEVED: 'Lấy danh sách cấu hình thành công',
  SETTING_RETRIEVED: 'Lấy thông tin cấu hình thành công',
  SETTING_UPSERTED: 'Lưu cấu hình thành công',
  SETTING_UPDATED: 'Cập nhật cấu hình thành công',
  USER_UPLOAD_PRESIGN_CREATED: 'Tạo URL tải tệp cho người dùng thành công',
  MANAGEMENT_UPLOAD_PRESIGN_CREATED: 'Tạo URL tải tệp cho hệ thống quản trị thành công',
  TEST_JOB_CREATED: 'Tạo tác vụ kiểm thử thành công',
  LOGGED_OUT: 'Đăng xuất thành công',
  PASSWORD_RESET_REQUESTED: 'Đã tạo hướng dẫn đặt lại mật khẩu',
  PASSWORD_RESET_SUCCESS: 'Đặt lại mật khẩu thành công',
  FACILITY_CREATED: 'Cơ sở y tế đã tạo thành công',
  FACILITY_UPDATED: 'Cơ sở y tế đã cập nhật thành công',
  FACILITY_DELETED: 'Cơ sở y tế đã xóa thành công',
  FACILITY_NOT_FOUND: 'Cơ sở y tế không tồn tại',
  FACILITY_ALREADY_EXISTS: 'Cơ sở y tế đã tồn tại',
  FACILITIES_RETRIEVED: 'Lấy danh sách cơ sở thành công',
  FACILITY_RETRIEVED: 'Lấy thông tin cơ sở thành công',
  FACILITY_STATUS_UPDATED: 'Cập nhật trạng thái cơ sở thành công',
  FACILITY_SELECTION_REQUIRED: 'Vui lòng chọn cơ sở làm việc.',
  FACILITY_ASSIGNMENT_INVALID: 'Cơ sở đang chọn không còn là nơi làm việc hợp lệ của bạn.',
  FACILITY_NOT_ASSIGNED: 'Bạn không thuộc cơ sở đã chọn.',
  FACILITY_ACCESS_DENIED: 'Bạn không có quyền truy cập dữ liệu của cơ sở này.',
} as const;
