export const RESPONSE_MESSAGES = {
  SUCCESS: 'Success',
  AUTH_REGISTERED: 'Registered successfully',
  AUTH_LOGGED_IN: 'Logged in successfully',
  AUTH_REFRESHED: 'Token refreshed successfully',
  AUTH_PROFILE_RETRIEVED: 'Authenticated profile retrieved successfully',
  PROFILE_RETRIEVED: 'Profile retrieved successfully',
  PROFILE_UPDATED: 'Profile updated successfully',
  MANAGEMENT_PROFILE_UPDATED: 'Cập nhật hồ sơ thành công.',
  MANAGEMENT_PASSWORD_CHANGED: 'Đổi mật khẩu thành công.',
  USERS_RETRIEVED: 'Users retrieved successfully',
  USER_CREATED: 'User created successfully',
  USER_RETRIEVED: 'User retrieved successfully',
  USER_UPDATED: 'User updated successfully',
  USER_DELETED: 'User deleted successfully',
  STAFF_PROFILE_CREATED: 'Tạo hồ sơ nhân viên thành công.',
  ROLES_RETRIEVED: 'Roles retrieved successfully',
  ROLE_CREATED: 'Role created successfully',
  ROLE_RETRIEVED: 'Role retrieved successfully',
  ROLE_UPDATED: 'Role updated successfully',
  ROLE_DELETED: 'Role deleted successfully',
  PERMISSIONS_RETRIEVED: 'Permissions retrieved successfully',
  PERMISSION_CREATED: 'Permission created successfully',
  PERMISSION_RETRIEVED: 'Permission retrieved successfully',
  PERMISSION_UPDATED: 'Permission updated successfully',
  PERMISSION_DELETED: 'Permission deleted successfully',
  PUBLIC_SETTINGS_RETRIEVED: 'Public settings retrieved successfully',
  SETTINGS_RETRIEVED: 'Settings retrieved successfully',
  SETTING_RETRIEVED: 'Setting retrieved successfully',
  SETTING_UPSERTED: 'Setting saved successfully',
  SETTING_UPDATED: 'Setting updated successfully',
  USER_UPLOAD_PRESIGN_CREATED: 'User presigned upload URL created successfully',
  MANAGEMENT_UPLOAD_PRESIGN_CREATED: 'Management presigned upload URL created successfully',
  TEST_JOB_CREATED: 'Test job created successfully',
  LOGGED_OUT: 'Logged out successfully',
  PASSWORD_RESET_REQUESTED: 'Password reset instructions have been generated',
  PASSWORD_RESET_SUCCESS: 'Password reset successfully',
} as const;
