export const RESPONSE_MESSAGES = {
  SUCCESS: 'Thành công',
  AUTH_REGISTERED: 'Đăng ký tài khoản thành công',
  AUTH_LOGGED_IN: 'Đăng nhập thành công',
  AUTH_REFRESHED: 'Làm mới mã xác thực thành công',
  AUTH_PROFILE_RETRIEVED: 'Lấy thông tin tài khoản xác thực thành công',
  PROFILE_RETRIEVED: 'Lấy thông tin hồ sơ thành công',
  PROFILE_UPDATED: 'Cập nhật hồ sơ thành công',
  MANAGEMENT_PROFILE_UPDATED: 'Cập nhật hồ sơ thành công.',
  MANAGEMENT_PASSWORD_CHANGED: 'Đổi mật khẩu thành công.',
  USERS_RETRIEVED: 'Lấy danh sách tài khoản thành công',
  USER_CREATED: 'Tạo tài khoản thành công',
  USER_RETRIEVED: 'Lấy thông tin tài khoản thành công',
  USER_UPDATED: 'Cập nhật tài khoản thành công',
  USER_DELETED: 'Xóa tài khoản thành công',
  STAFF_PROFILE_CREATED: 'Tạo hồ sơ nhân viên thành công.',
  ROLES_RETRIEVED: 'Lấy danh sách vai trò thành công',
  ROLE_CREATED: 'Tạo vai trò thành công',
  ROLE_RETRIEVED: 'Lấy thông tin vai trò thành công',
  ROLE_UPDATED: 'Cập nhật vai trò thành công',
  ROLE_DELETED: 'Xóa vai trò thành công',
  PERMISSIONS_RETRIEVED: 'Lấy danh sách quyền thành công',
  PERMISSION_CREATED: 'Tạo quyền thành công',
  PERMISSION_RETRIEVED: 'Lấy thông tin quyền thành công',
  PERMISSION_UPDATED: 'Cập nhật quyền thành công',
  PERMISSION_DELETED: 'Xóa quyền thành công',
  PUBLIC_SETTINGS_RETRIEVED: 'Lấy cấu hình công khai thành công',
  SETTINGS_RETRIEVED: 'Lấy danh sách cấu hình thành công',
  SETTING_RETRIEVED: 'Lấy thông tin cấu hình thành công',
  SETTING_UPSERTED: 'Lưu cấu hình thành công',
  SETTING_UPDATED: 'Cập nhật cấu hình thành công',
  USER_UPLOAD_PRESIGN_CREATED: 'Tạo URL tải tệp cho người dùng thành công',
  MANAGEMENT_UPLOAD_PRESIGN_CREATED: 'Tạo URL tải tệp cho hệ thống quản trị thành công',
  TEST_JOB_CREATED: 'Tạo tác vụ kiểm thử thành công',
  APPOINTMENTS: {
    CREATED: 'Đặt lịch thành công.',
    GET_LIST_SUCCESS: 'Lấy danh sách lịch đặt thành công.',
    GET_SUCCESS: 'Lấy chi tiết lịch đặt thành công.',
    CHECKED_IN: 'Check-in lịch khám thành công.',
    RESCHEDULED: 'Dời lịch khám thành công.',
    CANCELLED: 'Hủy lịch khám thành công.',
    NO_SHOW: 'Đánh dấu không đến thành công.',
    COMPLETED: 'Hoàn tất lịch khám thành công.',
    NOT_FOUND: 'Không tìm thấy lịch đặt khám.',
    NOT_FOUND_IN_FACILITY: 'Không tìm thấy lịch đặt khám trong cơ sở hiện tại.',
    CHECK_IN_STATUS_INVALID: 'Lịch này không thể check-in.',
    PROFILE_NOT_BELONG_TO_PATIENT: 'Hồ sơ thai kỳ không thuộc user đặt lịch.',
    SLOT_OUTSIDE_SHIFT: 'Slot đã chọn không nằm trong ca trực của bác sĩ.',
    DOCTOR_SHIFT_MISMATCH: 'Bác sĩ đã chọn không khớp với ca trực.',
    SLOT_JUST_BOOKED: 'Slot này vừa có người đặt. Bạn chọn khung giờ khác nhé.',
    END_TIME_AFTER_START_TIME: 'Giờ kết thúc phải sau giờ bắt đầu.',
    DOCTOR_SHIFT_NOT_AVAILABLE: 'Bác sĩ không có ca trực phù hợp với khung giờ này.',
    SLOT_CONFLICT: 'Slot này đã có lịch khác.',
    SERVICE_NOT_AVAILABLE_AT_FACILITY: 'Dịch vụ không khả dụng tại cơ sở đã chọn.',
    SHIFT_NOT_AVAILABLE: 'Ca trực không tồn tại hoặc không còn khả dụng.',
    SHIFT_ROOM_REQUIRED: 'Ca trực chưa có phòng khám để đặt lịch.',
  },
  SCHEDULES: {
    GET_LIST_SUCCESS: 'Lấy lịch cá nhân thành công.',
    CREATED: 'Tạo lịch cá nhân thành công.',
    DELETED: 'Xóa lịch cá nhân thành công.',
    NOT_FOUND: 'Không tìm thấy lịch cá nhân để xóa.',
  },
  LOGGED_OUT: 'Đăng xuất thành công',
  PASSWORD_RESET_REQUESTED: 'Đã tạo hướng dẫn đặt lại mật khẩu',
  PASSWORD_RESET_SUCCESS: 'Đặt lại mật khẩu thành công',
  FACILITY_CREATED: 'Cơ sở y tế đã tạo thành công',
  FACILITY_UPDATED: 'Cơ sở y tế đã cập nhật thành công',
  FACILITY_DELETED: 'Cơ sở y tế đã xóa thành công',
  FACILITY_NOT_FOUND: 'Cơ sở y tế không tồn tại',
  FACILITY_ALREADY_EXISTS: 'Cơ sở y tế đã tồn tại',
  FACILITIES_RETRIEVED: 'Lấy danh sách cơ sở thành công',
  FACILITY_RETRIEVED: 'Lấy thông tin cơ sở thành công',
  FACILITY_STATUS_UPDATED: 'Cập nhật trạng thái cơ sở thành công',
  FACILITY_SELECTION_REQUIRED: 'Vui lòng chọn cơ sở làm việc.',
  FACILITY_ASSIGNMENT_INVALID: 'Cơ sở đang chọn không còn là nơi làm việc hợp lệ của bạn.',
  FACILITY_NOT_ASSIGNED: 'Bạn không thuộc cơ sở đã chọn.',
  FACILITY_ACCESS_DENIED: 'Bạn không có quyền truy cập dữ liệu của cơ sở này.',
  PREGNANCY_PROFILES: {
    CREATED_SUCCESS: 'Hồ sơ mang thai đã được tạo thành công',
    GET_SUCCESS: 'Hồ sơ mang thai đã được lấy thành công',
    GET_LIST_SUCCESS: 'Danh sách hồ sơ mang thai đã được lấy thành công',
    NOT_FOUND: 'Hồ sơ mang thai không tồn tại',
    UPDATED: 'Hồ sơ mang thai đã được cập nhật thành công',
    DELETED: 'Hồ sơ mang thai đã được xóa tạm thời thành công',
    EXISTS: 'Hồ sơ mang thai đã tồn tại cho bệnh nhân này',
    PARA_CONFLICT:
      'Tổng số lần sinh con đủ tháng, sinh non và sảy thai không thể ít hơn số lần mang thai',
    NOT_IS_STAFF:
      'Chỉ nhân viên (bác sĩ, điều dưỡng hoặc nhân viên) mới có thể yêu cầu xóa tạm thời hồ sơ mang thai',
  },
  NOT_FOUND_CURRENT_USER: 'Người dùng hiện tại không tồn tại',
  INTERNAL_SERVER_ERROR: 'Lỗi máy chủ nội bộ',
  FACILITIES: {
    CREATED: 'Cơ sở y tế đã được tạo thành công',
    UPDATED: 'Cơ sở y tế đã được cập nhật thành công',
    DELETED: 'Cơ sở y tế đã được xóa thành công',
    GET_SUCCESS: 'Lấy thông tin cơ sở thành công',
    GET_LIST_SUCCESS: 'Lấy danh sách cơ sở thành công',
    LOOKUP_SUCCESS: 'Lấy danh sách gợi ý cơ sở thành công',
    ADMIN_OPTIONS_SUCCESS: 'Lấy danh sách admin có thể gán vào cơ sở thành công',
    OPERATING_HOURS_GET_SUCCESS: 'Lấy giờ hoạt động của cơ sở thành công',
    OPERATING_HOURS_PREVIEW_SUCCESS: 'Xem trước thay đổi giờ hoạt động thành công',
    OPERATING_HOURS_UPDATED: 'Cập nhật giờ hoạt động của cơ sở thành công',
    STATUS_UPDATED: 'Cập nhật trạng thái cơ sở thành công',
    NOT_FOUND: 'Cơ sở y tế không tồn tại',
    ALREADY_EXISTS: 'Cơ sở y tế đã tồn tại',
    OWNER_INVALID: 'ownerId không tồn tại, nhân viên đang ngừng hoạt động hoặc không có vai trò admin',
    DATE_RANGE_INVALID: 'fromDate phải nhỏ hơn hoặc bằng toDate',
    SCHEDULE_DAY_DUPLICATED: 'Một ngày không được khai báo trùng trong nhiều khung giờ',
    OPERATING_HOURS_HAS_IMPACTED_SHIFTS:
      'Không thể cập nhật giờ hoạt động vì còn ca trực sắp tới nằm ngoài khung giờ mới',
    OPERATING_STATUS_OPEN: 'Đang mở cửa',
    OPERATING_STATUS_CLOSED: 'Đã đóng cửa',
    OPERATING_STATUS_CLOSED_TODAY: 'Hôm nay đóng cửa',
    OPERATING_STATUS_INACTIVE: 'Cơ sở đang ngừng hoạt động',
    OWNER_ID_INVALID: 'ownerId phải là số nguyên dương',
    PHONE_INVALID: 'phone phải gồm 7-15 chữ số và có thể bắt đầu bằng dấu +',
    EMAIL_INVALID: 'email không đúng định dạng',
    LATITUDE_INVALID: 'latitude phải nằm trong khoảng -90 đến 90',
    LONGITUDE_INVALID: 'longitude phải nằm trong khoảng -180 đến 180',
    CREATE_DELETED_STATUS_INVALID: 'Không thể tạo cơ sở với trạng thái deleted',
    COORDINATE_PAIR_REQUIRED: 'Khi cập nhật tọa độ phải gửi cả latitude và longitude',
    OPEN_TIME_REQUIRED: 'openTime bắt buộc khi ngày không đóng cửa',
    OPEN_TIME_FORMAT_INVALID: 'openTime phải có định dạng HH:mm hoặc HH:mm:ss',
    CLOSE_TIME_REQUIRED: 'closeTime bắt buộc khi ngày không đóng cửa',
    CLOSE_TIME_FORMAT_INVALID: 'closeTime phải có định dạng HH:mm hoặc HH:mm:ss',
    CLOSE_TIME_AFTER_OPEN_TIME: 'closeTime phải muộn hơn openTime',
  },
  FACILITY_CLOSURE_DAYS: {
    CREATED: 'Ngày đóng cửa của cơ sở đã được tạo thành công',
    UPDATED: 'Ngày đóng cửa của cơ sở đã được cập nhật thành công',
    DELETED: 'Ngày đóng cửa của cơ sở đã được xóa thành công',
    GET_LIST_SUCCESS: 'Lấy danh sách ngày đóng cửa của cơ sở thành công',
    NOT_FOUND: 'Ngày đóng cửa của cơ sở không tồn tại',
    ALREADY_EXISTS: 'Ngày đóng cửa của cơ sở đã tồn tại',
    DATE_FORMAT_INVALID: 'closureDate phải có định dạng YYYY-MM-DD',
    FROM_DATE_FORMAT_INVALID: 'fromDate phải có định dạng YYYY-MM-DD',
    TO_DATE_FORMAT_INVALID: 'toDate phải có định dạng YYYY-MM-DD',
  },
  ROOMS: {
    CREATED: 'Tạo phòng thành công',
    UPDATED: 'Cập nhật phòng thành công',
    DELETED: 'Xóa phòng thành công',
    GET_LIST_SUCCESS: 'Lấy danh sách phòng thành công',
    GET_SUCCESS: 'Lấy thông tin phòng thành công',
    GET_BY_FACILITY_SUCCESS: 'Lấy danh sách phòng theo cơ sở thành công',
    LOOKUP_SUCCESS: 'Lấy danh sách gợi ý phòng thành công',
    BULK_PREVIEW_SUCCESS: 'Xem trước tạo phòng hàng loạt thành công',
    BULK_CONFIRM_SUCCESS: 'Tạo phòng hàng loạt thành công',
    NOT_FOUND: 'Phòng không tồn tại',
    ALREADY_EXISTS: 'Phòng đã tồn tại',
    STATUS_UPDATED: 'Cập nhật trạng thái phòng thành công',
    BULK_NO_VALID_ROOM: 'Không có phòng hợp lệ để tạo',
    BULK_STRICT_HAS_ISSUES:
      'Còn phòng bị bỏ qua hoặc xung đột nên không thể confirm ở chế độ strict',
    BULK_DUPLICATED_IN_PAYLOAD: 'Danh sách tạo phòng có phòng bị trùng tên trong cùng cơ sở',
    BULK_DUPLICATED_REASON: 'Tên phòng bị trùng trong payload tại cùng cơ sở',
    BULK_INVALID_ROOM_DATA: 'Dữ liệu phòng không hợp lệ',
    BULK_CHECK_FAILED: 'Không thể kiểm tra phòng này',
    FACILITY_INACTIVE: 'Cơ sở không hoạt động nên không thể tạo phòng',
    FACILITY_ID_INVALID: 'facilityId phải là số nguyên dương',
    ROOM_TYPE_ID_INVALID: 'roomTypeId phải là số nguyên dương',
  },
  ROOM_TYPES: {
    CREATED: 'Tạo loại phòng thành công',
    UPDATED: 'Cập nhật loại phòng thành công',
    DELETED: 'Xóa loại phòng thành công',
    GET_LIST_SUCCESS: 'Lấy danh sách loại phòng thành công',
    GET_SUCCESS: 'Lấy thông tin loại phòng thành công',
    LOOKUP_SUCCESS: 'Lấy danh sách gợi ý loại phòng thành công',
    GET_BY_FACILITY_SUCCESS: 'Lấy danh sách loại phòng theo cơ sở thành công',
    NOT_FOUND: 'Loại phòng không tồn tại',
    ACTIVE_NOT_FOUND: 'Loại phòng không tồn tại hoặc đang ngừng hoạt động',
    ALREADY_EXISTS: 'Loại phòng đã tồn tại',
  },
  SHIFTS: {
    CREATED: 'Tạo ca trực bác sĩ thành công',
    UPDATED: 'Cập nhật ca trực bác sĩ thành công',
    DELETED: 'Xóa ca trực bác sĩ thành công',
    FOUND: 'Lấy danh sách ca trực bác sĩ thành công',
    DETAIL_FOUND: 'Lấy chi tiết ca trực bác sĩ thành công',
    CHECK_CONFLICT_SUCCESS: 'Kiểm tra xung đột ca trực thành công',
    BULK_CREATED: 'Tạo ca trực hàng loạt thành công',
    AUTO_GENERATE_PREVIEW_SUCCESS: 'Xem trước lịch trực tự động thành công',
    AUTO_GENERATE_CONFIRM_SUCCESS: 'Tạo lịch trực tự động thành công',
    BULK_GENERATE_PREVIEW_SUCCESS: 'Xem trước lịch trực hàng loạt thành công',
    BULK_GENERATE_CONFIRM_SUCCESS: 'Tạo lịch trực hàng loạt thành công',
    COPY_WEEK_SUCCESS: 'Copy lịch trực theo tuần thành công',
    AVAILABILITY_SUCCESS: 'Lấy lịch trống của bác sĩ thành công',
    WEEKLY_SUCCESS: 'Lấy lịch trực theo tuần thành công',
    NOT_FOUND: 'Ca trực bác sĩ không tồn tại',
    DOCTOR_NOT_ASSIGNED: 'Bác sĩ không hoạt động hoặc chưa được phân công tại cơ sở này',
    ROOM_INVALID: 'Phòng không hoạt động hoặc không thuộc cơ sở của ca trực',
    FACILITY_INACTIVE: 'Không thể xếp ca tại cơ sở không hoạt động',
    DOCTOR_CONFLICT: 'Bác sĩ đã có ca trực trùng thời gian',
    ROOM_CONFLICT: 'Phòng đã được sử dụng bởi ca trực khác trong khoảng thời gian này',
    FACILITY_ID_REQUIRED: 'facilityId là bắt buộc',
    SHIFT_ID_INVALID: 'shiftId phải là số nguyên dương',
    END_TIME_AFTER_START_TIME: 'endTime phải muộn hơn startTime',
    DURATION_INVALID: 'Thời lượng ca trực phải từ 15 phút đến 12 giờ',
    PAST_DATE_INVALID: 'Không thể tạo hoặc kiểm tra ca trực trong quá khứ',
    OFF_SHIFT_CANNOT_HAVE_ROOM: 'Ca nghỉ không được gán phòng',
    FACILITY_CLOSED_ON_DATE: 'Cơ sở đóng cửa trong ngày được chọn',
    FACILITY_HOURS_NOT_CONFIGURED: 'Cơ sở chưa cấu hình đầy đủ giờ hoạt động cho ngày được chọn',
    FACILITY_HOURS_INVALID: 'Ca trực phải nằm trong giờ hoạt động của cơ sở',
    DATE_RANGE_INVALID: 'dateFrom phải sớm hơn hoặc bằng dateTo',
    BULK_RANGE_TOO_SHORT: 'Tạo ca hàng loạt phải có khoảng thời gian tối thiểu 7 ngày',
    BULK_RANGE_REQUIRED: 'Cần gửi toDate hoặc durationDays khi tạo ca hàng loạt',
    BULK_RANGE_AMBIGUOUS: 'Chỉ được gửi một trong hai trường toDate hoặc durationDays',
    BULK_NO_MATCHING_DATE: 'Không có ngày nào khớp với workingDays trong khoảng đã chọn',
    BULK_RANGE_TOO_LONG: 'Chỉ được tạo ca hàng loạt tối đa trong 92 ngày mỗi lần',
    AUTO_GENERATE_RANGE_TOO_LONG: 'Chỉ được auto-generate tối đa trong 92 ngày mỗi lần',
    AUTO_GENERATE_NO_VALID_SHIFT: 'Không có ca trực hợp lệ để tạo',
    AUTO_GENERATE_STRICT_HAS_ISSUES:
      'Còn ca bị bỏ qua hoặc xung đột nên không thể confirm ở chế độ strict',
    AUTO_GENERATE_CLOSURE_DAY: 'Cơ sở đóng cửa trong ngày này',
    AUTO_GENERATE_CONFLICT: 'Ca trực bị trùng lịch bác sĩ hoặc phòng',
    AUTO_GENERATE_CANDIDATE_FAILED: 'Không thể tạo candidate ca trực',
    SLOT_LOCKED_TIME_CHANGE:
      'Ca đang dùng slotId; nếu muốn đổi giờ thủ công hãy gửi slotId = null cùng startTime/endTime',
    COPY_WEEK_SAME_TARGET: 'targetWeekStart phải khác sourceWeekStart',
    SLOT_TIME_SENT_WITH_SLOT_ID:
      'Khi dùng slotId thì không gửi startTime/endTime để tránh lệch dữ liệu khung ca',
    SLOT_INACTIVE_OR_NOT_FOUND: 'Khung ca không tồn tại hoặc đã ngừng hoạt động',
    SLOT_NOT_BELONG_TO_FACILITY: 'Khung ca không thuộc cơ sở đang tạo lịch trực',
    TIME_REQUIRED_WITHOUT_SLOT: 'Cần gửi startTime và endTime khi không dùng slotId',
    CREATE_STATUS_INVALID: 'Ca mới chỉ có thể ở trạng thái available hoặc off',
    BULK_STATUS_INVALID: 'Ca tạo hàng loạt chỉ có thể ở trạng thái available hoặc off',
    SHIFT_DATE_FORMAT_INVALID: 'shiftDate phải có định dạng YYYY-MM-DD',
  },
  SHIFT_SLOTS: {
    GET_LIST_SUCCESS: 'Lấy danh sách khung ca thành công',
    LOOKUP_SUCCESS: 'Lấy gợi ý khung ca thành công',
    GET_SUCCESS: 'Lấy chi tiết khung ca thành công',
    CREATED: 'Tạo khung ca thành công',
    UPDATED: 'Cập nhật khung ca thành công',
    DELETED: 'Xóa khung ca thành công',
    NOT_FOUND: 'Khung ca không tồn tại',
    DUPLICATED: 'Khung ca đã tồn tại trong phạm vi này',
    FACILITY_INACTIVE: 'Cơ sở không hoạt động nên không thể cấu hình khung ca',
    END_TIME_AFTER_START_TIME: 'endTime phải muộn hơn startTime',
    TIME_OVERLAP: 'Khung giờ bị chồng lấn với khung ca đang hoạt động trong cùng cơ sở',
    OUTSIDE_FACILITY_HOURS: 'Khung ca không nằm trong bất kỳ ngày mở cửa nào của cơ sở',
    CODE_GENERATE_FAILED: 'Không thể sinh mã khung ca duy nhất',
    ID_INVALID: 'shiftSlotId phải là số nguyên dương',
    FACILITY_ID_INVALID: 'facilityId phải là số nguyên dương',
    START_TIME_FORMAT_INVALID: 'Giờ bắt đầu phải có định dạng HH:mm hoặc HH:mm:ss',
    END_TIME_FORMAT_INVALID: 'Giờ kết thúc phải có định dạng HH:mm hoặc HH:mm:ss',
  },
} as const;
