import { RESPONSE_MESSAGES } from './response-message.constant';

/**
 * Alias giữ tương thích cho code/test cũ.
 * Source message chính của phòng/loại phòng nằm ở RESPONSE_MESSAGES.ROOMS và RESPONSE_MESSAGES.ROOM_TYPES.
 */
export const ROOM_CONSTANT = {
  CREATED_SUCCESSFULLY: RESPONSE_MESSAGES.ROOMS.CREATED,
  UPDATED_SUCCESSFULLY: RESPONSE_MESSAGES.ROOMS.UPDATED,
  DELETED_SUCCESSFULLY: RESPONSE_MESSAGES.ROOMS.DELETED,

  ROOM_NOT_FOUND: RESPONSE_MESSAGES.ROOMS.NOT_FOUND,
  ROOM_ALREADY_EXISTS: RESPONSE_MESSAGES.ROOMS.ALREADY_EXISTS,
  ROOM_FOUND: RESPONSE_MESSAGES.ROOMS.GET_LIST_SUCCESS,
  ROOM_DETAIL_FOUND: RESPONSE_MESSAGES.ROOMS.GET_SUCCESS,
  ROOM_STATUS_UPDATED: RESPONSE_MESSAGES.ROOMS.STATUS_UPDATED,

  ROOM_TYPE_CREATED_SUCCESSFULLY: RESPONSE_MESSAGES.ROOM_TYPES.CREATED,
  ROOM_TYPE_UPDATED_SUCCESSFULLY: RESPONSE_MESSAGES.ROOM_TYPES.UPDATED,
  ROOM_TYPE_DELETED_SUCCESSFULLY: RESPONSE_MESSAGES.ROOM_TYPES.DELETED,
  ROOM_TYPE_FOUND: RESPONSE_MESSAGES.ROOM_TYPES.GET_LIST_SUCCESS,
  ROOM_TYPE_DETAIL_FOUND: RESPONSE_MESSAGES.ROOM_TYPES.GET_SUCCESS,
  ROOM_TYPE_NOT_FOUND: RESPONSE_MESSAGES.ROOM_TYPES.NOT_FOUND,
  ROOM_TYPE_ALREADY_EXISTS: RESPONSE_MESSAGES.ROOM_TYPES.ALREADY_EXISTS,
} as const;
