export const SERVICE_CONSTANT = {
  CREATED: 'Tạo dịch vụ thành công',
  UPDATED: 'Cập nhật dịch vụ thành công',
  DELETED: 'Xóa dịch vụ thành công',
  FOUND: 'Lấy danh sách dịch vụ thành công',
  DETAIL_FOUND: 'Lấy chi tiết dịch vụ thành công',
  NOT_FOUND: 'Không tìm thấy dịch vụ',
  CODE_EXISTS: 'Mã dịch vụ đã tồn tại',
  NAME_EXISTS: 'Tên dịch vụ đã tồn tại',
  TYPE_CREATED: 'Tạo loại dịch vụ thành công',
  TYPE_UPDATED: 'Cập nhật loại dịch vụ thành công',
  TYPE_DELETED: 'Xóa loại dịch vụ thành công',
  TYPE_FOUND: 'Lấy danh sách loại dịch vụ thành công',
  TYPE_DETAIL_FOUND: 'Lấy chi tiết loại dịch vụ thành công',
  TYPE_LOOKUP_FOUND: 'Lấy danh sách gợi ý loại dịch vụ thành công',
  TYPE_NOT_FOUND: 'Không tìm thấy loại dịch vụ',
  TYPE_ACTIVE_NOT_FOUND: 'Loại dịch vụ không tồn tại hoặc đang ngừng hoạt động',
  TYPE_NAME_EXISTS: 'Tên loại dịch vụ đã tồn tại',
  PRICE_INVALID: 'Giá dịch vụ phải là số tiền không âm, tối đa 13 chữ số phần nguyên và 2 chữ số thập phân',
  FACILITY_ID_INVALID: 'Mã cơ sở phải là số nguyên dương',
  TYPE_ID_INVALID: 'Mã loại dịch vụ phải là số nguyên dương',
  NAME_INVALID: 'Tên dịch vụ phải có từ 2 đến 200 ký tự',
  DESCRIPTION_INVALID: 'Mô tả dịch vụ không được vượt quá 2000 ký tự',
  DURATION_INVALID: 'Thời lượng dịch vụ phải là số nguyên từ 5 đến 480 phút',
  SALE_MODE_INVALID: 'Hình thức bán dịch vụ không hợp lệ',
  DOCTOR_REQUIREMENT_INVALID: 'Quy định yêu cầu bác sĩ phải là giá trị đúng hoặc sai',
  STATUS_INVALID: 'Trạng thái dịch vụ không hợp lệ',
  FACILITY_ASSIGNMENTS_INVALID: 'Danh sách cơ sở áp dụng phải có ít nhất một cơ sở và không được trùng',
  SEARCH_INVALID: 'Từ khóa tìm kiếm phải là chuỗi hợp lệ',
  PAGE_INVALID: 'Số trang phải là số nguyên dương',
  LIMIT_INVALID: 'Số bản ghi mỗi trang phải là số nguyên từ 1 đến 200',
};
